version: "2"
services:
 flask:
  build:
   context: .
   dockerfile: python-Dockerfile
  container_name: myflask
  ports:
   - 5000:5000

 proxy:
  build:
   context: .
   dockerfile: nginx-Dockerfile
  container_name: myproxy
  ports:
   - 80:80
  links:
   - flask


